baseURL = "https://2018.alinaelumr.de/"
languageCode = "de-de"
title = "alínæ lumr Festival 2018"

theme = "al-2018"

# doesn't work yet (hugo bug, see https://github.com/SiamKreative/siamkreative.com/issues/20)
# leaving this here in case someone fixes this at some point...
ignoreFiles = ['\\.scss$']

[params]
    description = "Zum vierten Mal lädt das alínæ lumr an einem Augustwochenende zu einem ereignisreichen Urlaub auf dem Land. Auf der Burg, am Marktplatz, den Hinterhöfen, der Altstadtkirche, auf versteckten Wiesen und am See wartet unser sorgfältig kuratiertes Musikprogramm, Workshops, Theater, Lesungen und die charmante Altstadt Storkow auf euch. Wir möchten die Stadt öffnen und Orte des Zusammenkommens schaffen, auch um ein klares Zeichen für positiven Austausch und Willkommenskultur in der Region zu setzen."

[blackfriday]
    hrefTargetBlank = true

[markup.goldmark.renderer]
    unsafe= true
