version: 2
jobs:
  build:
    docker:
      # - image: debian:stretch
      # - image: circleci/golang
      - image: circleci/node:8
    
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      
      - run: yarn install
      # - run: pwd
      # - run: find .
      - run: ./node_modules/.bin/gulp scss
      - run: rm -rf ./node_modules
      
      # prepare for deployment
      - run:
          name: Fix host authenticity for elnath.uberspace.de
          command: |
            ssh-keyscan elnath.uberspace.de >> ~/.ssh/known_hosts
      
      # "deploy"
      - deploy:
          name: copy to alu.uberspace.de
          command: scp -r ./* alu@elnath.uberspace.de:~/website-2018-hugo/