version: 2
jobs:
  build:
    docker:
      # - image: debian:stretch
      - image: circleci/node:8
      # - image: circleci/node@sha256:895bd70ebcf4fd8a61a38f236fdea711859ac5d24357dc419559e53b06bac476
    
    working_directory: ~/repo

    steps:
      - run: sudo apt install rsync

      - checkout
      
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      
      - run: 
          name: parse sass/scss
          command: ./node_modules/.bin/gulp scss

      - run: 
          name: see if bands from trello updated
          command: ./node_modules/.bin/gulp getBandsHash

      - run: cat static/bands.hash
      
      - restore_cache:
          name: Restore band images
          keys:
            - band-images-{{ checksum "static/bands.hash" }}

      - run: 
          name: get Bands from trello
          command: ./node_modules/.bin/gulp getBands
      
      - save_cache:
          name: Save band images
          key: band-images-{{ checksum "static/bands.hash" }}
          paths:
            - content/bands

      - run:
          name: cleanup before copy - remove node_modules
          command: rm -rf ./node_modules
      
      # prepare for deployment
      - run:
          name: Fix host authenticity for elnath.uberspace.de
          command: ssh-keyscan elnath.uberspace.de >> ~/.ssh/known_hosts
      
      # "deploy"
      - deploy:
          name: copy to alu.uberspace.de
          # command: scp -r ./* alu@elnath.uberspace.de:~/website-2018-hugo/
          command: rsync -rlOz --force --delete ./* alu@elnath.uberspace.de:~/website-2018-hugo/
      
      # restart hugo serve
      - run:
          name: Restart hugo serve
          command: ssh alu@elnath.uberspace.de "svc -h ~/service/al-2018-hugo/"

workflows:
  version: 2
  do_build: 
    jobs: 
      - build
  scheduled_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0,15,30,45 0,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *"
          filters:
            branches:
              only:
                - master
  # manual_build:
  #   jobs:
  #     - build:
  #         type: approval
